### PR TITLE
Update CMake to 3.21.1

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by vsoch** [comment]
Looks like this didn't trigger a build since we didn't change any files - should we do a trivial change to some of the containers to ensure the builds still work? E.g.,, add a changed comment or newline (or similar)?

**Comment by davidbeckingsale** [comment]
> Looks like this didn't trigger a build since we didn't change any files - should we do a trivial change to some of the containers to ensure the builds still work? E.g.,, add a changed comment or newline (or similar)?

Will do!

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
And next time we need to trigger, we can delete that comment :laughing:

**Comment by rhornung67** [comment]
@davidbeckingsale was this change based on our discussion at the RAJA meeting yesterday? If so, we actually need cmake 3.23 for HIP.

**Comment by vsoch** [comment]
Fixed!

**Comment by rhornung67** [comment]
No worries. I was confused.

**Pull request merged**
