### PR TITLE
Trying a fix for mesa with llvm bug

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
This will address #81 (the meson is fixed but this looks to be something new)

**Comment by vsoch** [comment]
@trws same error as before with same builds, so that wasn't the fix. What else can we try? 
image

**Comment by trws** [comment]
Now I'm guessing it's a version problem.  If LLVM is there and a symbol is not that's the most likely culprit.  These could really use a version bump anyway, we probably should be building only 4.5.2 and maybe a 4.3.  Really it should be a 5.0, but those aren't in the package yet.  Maybe try bumping the version and see if it works ok?

**Comment by vsoch** [comment]
That's a good idea to try. And over time, our builds are going to change. We will always provide the previously successfully built containers, but we won't provide updated builds for them after they essentially stop working.

**Comment by trws** [comment]
It's especially necessary for things like this, AMD's stack is changing so fast, and so unstable in some ways that trying to keep all of them working long term is going to get painful fast.

**Comment by vsoch** [comment]
That's weird it says it's unsatisfiable - perhaps one of the deps we've hard coded?
```
==> Error: hip@4.5.2 is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
```
There definitely is a 4.5.2 under safe versions!

**Comment by trws** [comment]
Wait, is it still using the older patched out of tree hip package? That might be part of the problem too if the upstream diverged.

**Comment by vsoch** [comment]
>older patched out of tree hip package

I don't know - is it? What should I try?

**Comment by trws** [comment]
I’ll look.  I remember you or someone made a copy of the hip package to apply the cyclades patch at some point, if that’s still there the new version wouldn’t be in the old file.

**Comment by vsoch** [comment]
oh right! Well minimally I can test removing using that first.

**Pull request merged**
