### PR TITLE
Add llvm-amdgpu to view in HIP Dockerfile

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by vsoch** [comment]
@davidbeckingsale I've seen this before and I think it's a transient error can you double check? https://github.com/rse-ops/docker-images/runs/5190402898?check_suite_focus=true I can ignore it if it's not related to the PR here.

**Comment by davidbeckingsale** [comment]
Yup, looks like a transient issue to me.

**Comment by vsoch** [comment]
cool beans, thanks!

**Comment by davidbeckingsale** [comment]
and I really hope this is the last tweak to this image 😄

**Review by vsoch — APPROVED** [review]

**Pull request merged**
