### PR TITLE
Add HIP 5.0.2

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by vsoch** [comment]
@davidbeckingsale do we want to remove 4.3.1?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale do we want to remove 4.3.1?

Looks like both the 4 versions are failing 😭 let me see if they are fixable and then we can decide which to keep.

**Comment by vsoch** [comment]
@davidbeckingsale 4.5.2 still failing (4.3.1 wait to be seen)

**Comment by vsoch** [comment]
go hip go!!!

**Comment by davidbeckingsale** [comment]
🤞

**Comment by vsoch** [comment]
@davidbeckingsale can we remove the older builds (or add to skip?)

**Comment by davidbeckingsale** [comment]
Yup, I'll remove the old builds.

**Comment by davidbeckingsale** [comment]
@vsoch I think this is good - the failing builds on the last commits are 4.x versions which I removed already. I'm not 100% sure why they were showing up.

**Comment by vsoch** [comment]
Did the cancelled one work before?

**Comment by vsoch** [comment]
The failed ones might have just been before you refreshed the page? Anyhoo this is good to merge when that last one passes!

**Comment by vsoch** [comment]
ahh so I think it might have gone over time?

**Comment by vsoch** [comment]
That's really strange that 22.04 times out (> 6 hours) and not 20.04. The other 22.04/20.04 combo is also about an hour difference. Can we figure out why 22.04 is slower and (is there something we can do to the image) to make the build faster? Or a cache of some kind for spack? I'm guessing these won't hit the official spack build cache (because I never can) but perhaps we could either:

- split some of the build time into a base image 
- some kind of cache that can be shared between runners?
- or just remove that particular combination (22.04 and 5.1.3) for the time being!

**Comment by vsoch** [comment]
Added with #96

**Pull request closed without merging**
